# Python CircleCI 2.0 configuration file
# vi: et:ts=2:sw=2

version: 2.0

jobs:
  python_27:
    docker:
      - image: circleci/python:2.7
        environment: &env
          VERSION: 2.16.11
          CC: /usr/lib/ccache/cc
          C_INCLUDE_PATH: /usr/local/include:/usr/include
          LD_LIBRARY_PATH: /usr/local/lib:/usr/lib
    working_directory: ~/python-mbedtls
    steps: &steps
      - checkout
      - run: &deps
          name: Install dependencies
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq install ccache
            echo "export PATH=/usr/lib/ccache:$PATH" >> $BASH_ENV
      - run: &python_version
          name: Display current Python
          command: python -VV | tee python_version
      - restore_cache: &restore_cache_ccache
          keys:
            - ccache--v0--{{ checksum "python_version" }}
      - run: &mbedtls
          name: Install mbedtls
          command: |
            sudo ./scripts/download-mbedtls.sh $VERSION /usr/local/src
            sudo ./scripts/install-mbedtls.sh /usr/local/src
      - run: &install
          name: Install library
          command: |
            python setup.py sdist -d dist
            python setup.py bdist_wheel
            python -m pip install --user --upgrade dist/*.whl
      - save_cache: &save_cache_ccache
          key: ccache--v0--{{ checksum "python_version" }}--{{ .BuildNum }}
          paths:
            - /home/circleci/.ccache
      - run: &tests
          name: Run tests
          command: |
            python -m pip install --user -r requirements/tests.txt
            python -m pytest --junitxml="test-results/result.xml"
      - store_test_results:
          path: test-results
      - store_artifacts: &archive_dist
          path: dist



  python_37:
    docker: &qa
      - image: circleci/python:3.7
        environment: *env
    working_directory: ~/python-mbedtls
    steps: *steps



workflows:
  version: 2
  build:
    jobs:

      - python_37
