name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        version: [2.16.9]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Build and test wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp3{6,7,8,9}-*
          CIBW_SKIP: "*-win32 *-manylinux_i686"
          CIBW_ENVIRONMENT: VERSION=${{ matrix.version }}
          CIBW_BEFORE_ALL_LINUX: >
            ./scripts/download-mbedtls.sh $VERSION ~/.local/src
            && ./scripts/install-mbedtls.sh ~/.local/src
          CIBW_BEFORE_ALL_MACOS: >
            ./scripts/download-mbedtls.sh $VERSION ~/.local/src
            && ./scripts/install-mbedtls.sh ~/.local/src
            && cp /usr/local/lib/libmbed*dylib .
          #CIBW_BEFORE_ALL_WINDOWS:
          CIBW_TEST_REQUIRES: -rrequirements/tests.txt
          CIBW_TEST_COMMAND: pytest {project}/tests

      - name: Inventory
        run: ls wheelhouse
